version: '3.8'

services:
  app:
    image: sushi-app
    ports:
      - 8080:8080
    depends_on:
      - sushi-db

  sushi-db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=sushi
      - POSTGRES_USER=sushi
      - POSTGRES_DB=sushi
    ports:
      - 5499:5432